---
- name: Base - Install apt packages
  apt:
    name: "{{ essential_packages_apt }}"
    state: present
    update_cache: yes

- name: Base - Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop: "{{ essential_packages_pipx }}"

- name: Base - Copy wallpapers
  copy:
    src: wallpapers/
    dest: "/home/{{ username }}/wallpapers/"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0644"