# Docker Repo
docker_apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_key_dest: /etc/apt/keyrings/docker.asc
docker_apt_repo_url: "deb [arch=amd64 signed-by={{ docker_apt_key_dest }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

docker_force_requests_version: false
