---
- name: Qtile - Install necessary packages
  apt:
    name:
      - xserver-xorg
      - xinit
      - libpangocairo-1.0-0
      - python3-pip
      - python3-xcffib
      - python3-cairocffi
    state: present
    update_cache: true

- name: Qtile - Install qtile
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
    - qtile

- name: Qtile - add qtile to path
  command:
    cmd: pipx ensurepath
  changed_when: false

- name: Qtile - Install required Python packages
  ansible.builtin.command:
    cmd: pipx runpip qtile install qtile_extras psutil dbus-next dbus-fast
  changed_when: False

- name: Qtile - Ensure configuration directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ qtile_config_directory }}"
    - "{{ qtile_config_directory }}/scripts"
    - "{{ picom_config_directory }}"
    
- name: Qtile - Copy qtile scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ qtile_config_directory }}/scripts/{{ item }}"
    mode: '0755'
  loop:
    - wallpaper.sh
    - autostart.sh

- name: Qtile - Create Qtile desktop entry
  template:
    src: qtile.desktop.j2
    dest: /usr/share/xsessions/qtile.desktop
    mode: '0644'

- name: Qtile - Copy qtile configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ qtile_config_directory }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: '0644'
  loop:
    - colors.py
    - config.py

- name: Qtile - Copy pciom configuration file
  template:
    src: config.py.j2
    dest: "{{ picom_config_directory }}/picom.conf"
    mode: '0644'