---
- name: Qtile - Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - xserver-xorg
    - xinit
    - libpangocairo-1.0-0
    - python3-pip
    - python3-xcffib
    - python3-cairocffi

- name: Qtile - Ensure pipx is installed
  apt:
    name: pipx
    state: present
    update_cache: true

- name: Qtile - Install qtile its dependencies
  community.general.pipx:
    name: "{{ qtile }}"
    state: present
  loop:
    - qtile
    - qtile-extras
    - psutil
    - dbus-next
    - dbus-fast

- name: Qtile - add qtile to path
  command:
    cmd: pipx ensurepath
  changed_when: false

# - name: Install required Python packages for Qtile
#   ansible.builtin.command:
#     cmd: pipx runpip qtile install qtile_extras psutil dbus-next
#   register: qtile_install_results
#   changed_when: False

- name: Qtile - Ensure configuration directory exists
  file:
    path: "{{ qtile_config_directory }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ qtile_config_directory }}"
    - "{{ qtile_config_directory }}/scripts/"
    
- name: Qtile - Copy qtile scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ qtile_config_directory }}/scripts/{{ item }}"
    mode: '0755'
  loop:
    - wallpaper.sh
    - autostart.sh

- name: Qtile - Create Qtile desktop entry
  template:
    src: qtile.desktop.j2
    dest: /usr/share/xsessions/qtile.desktop
    mode: '0644'

- name: Qtile - Copy qtile configuration file
  template:
    src: config.py.j2
    dest: "{{ qtile_config_directory }}/config.py"
    mode: '0644'