---
- name: Libvirt - Update package lists
  apt:
    update_cache: yes

- name: Libvirt - Install required packages
  apt:
    name:
      - vagrant
      - qemu-kvm
      - libvirt-daemon-system
      - ebtables
      - libguestfs-tools
      - ruby-fog-libvirt
    state: present

- name: Libvirt - Add default user to virt-manager group
  user:
    name: "{{ username }}"
    state: present
    groups:
      - libvirt
    append: yes

- name: Libvirt - Check if vagrant-libvirt plugin is installed
  command: vagrant plugin list
  register: vagrant_plugins
  changed_when: false
  ignore_errors: true

- name: Libvirt - Install vagrant-libvirt plugin
  command: vagrant plugin install vagrant-libvirt
  when: "'vagrant-libvirt' not in vagrant_plugins.stdout"