galaxy_info:
  author: DevOps Department
  description: Docker engine
  company: 42.solutions
  role_name: docker
  namespace: docker
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - docker

dependencies: []
